### ISSUE TITLE
I'm getting this error when I'm trying to open the viewer.

### ISSUE THREAD

**Issue by rodoabad** [satyagraha/gfm_viewer#73]
`Plug-in code.satyagraha.gfm.viewer.plugin was unable to load class code.satyagraha.gfm.viewer.views.MarkdownViewDefault.`

**Comment by satyagraha** [comment]
Now explicitly requires execution environment JavaSE-1.7.
Fixed in 1.9.3.

**Comment by paulvi** [comment]
What version is recommended for Java 6 users ?

**Comment by satyagraha** [comment]
There is no version which works (properly) with Java 6. In theory, I could remove the use of the AutoCloseable interface, but I wouldn't test the code as I don't have Java 6 installed and don't intend to reinstall it. It went EOL in Februrary 2013. Users can have both JVM versions installed if they wish, and use the neat solution proposed above by @renelink. 

Java 8 will soon be an essential install, e.g. for Scala 2.12, but I will stick with Java 7 for the plugin.

**Comment by paulvi** [comment]
> Now explicitly requires execution environment JavaSE-1.7.

How? I know only p2 repository filter by OS

**Comment by satyagraha** [comment]
See the change at line 20 at https://github.com/satyagraha/gfm_viewer/commit/69d7188de6a460438fe6b8fa02e15ce2370489ad#diff-15

**Comment by satyagraha** [comment]
Eclipse will not load the plugin if it cannot provide the specified environment, and will give a reasonably comprehensible error message, i.e. not an exception with a traceback..

**Comment by paulvi** [comment]
OK, then no need for docs update
