### ISSUE TITLE
GFMV actions are in improper places

### ISSUE THREAD

**Issue by paulvi** [satyagraha/gfm_viewer#74]
Sometimes GFMV actions (Show in GFM View, Generate Markdown Preview) are in improper places.

For example in History Vew (clicked file is .java)

![gfmv actions are in improper places](https://cloud.githubusercontent.com/assets/1614482/5913084/c0530470-a618-11e4-981f-cd10ced58b42.png)

I guess there should be some filter...

**Comment by satyagraha** [comment]
The appearance of these menu entries is controlled here:

![capture](https://cloud.githubusercontent.com/assets/178885/5927604/9231fe4a-a66b-11e4-9d00-c1d143e19573.PNG)

It isn't particularly simple.
