### ISSUE TITLE
Are tables supported?

### ISSUE THREAD

**Issue by PKRoma** [satyagraha/gfm_viewer#76]
Quick question: Are tables supported in 1.9.3? I can't get the following GFM to show up in GFM View visualised as a table:

Planet|Distance|Period
-|-|-
Earth|150000000 km|1 year

**Comment by satyagraha** [comment]
You need three dashes in the second line, see
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables
