### ISSUE TITLE
Nested lists not supported?

### ISSUE THREAD

**Issue by cupdike** [satyagraha/gfm_viewer#79]
When previewed in Eclipse, this nested list: 

```
* Top level
  * Sub level
```

Should render like this two level list:
- Top level
  - Sub level

But renders as a single level list:
- Top level
- Sub level

**Comment by satyagraha** [comment]
It's working fine for me. Have you enabled all the auto-linking etc?
You may need to give full information on versions, environment etc.

**Comment by satyagraha** [comment]
Closing presuming not an issue; if disagree, please reopen including a link to a repo illustrating the problem.
