### ISSUE TITLE
error MD when install the GFM

### ISSUE THREAD

**Issue by yananzhi** [satyagraha/gfm_viewer#82]
Use https://raw.githubusercontent.com/satyagraha/gfm_viewer/master/p2-composite/ to install the GFM, there has follow error msg 
```
An error occurred while collecting items to be installed
session context was:(profile=epp.package.cpp, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Problems downloading artifact: osgi.bundle,code.satyagraha.gfm.viewer.plugin,1.9.3.
MD5 hash is not as expected. Expected: dcdc7953e7e1135179d49b296d038774 and found e524475e73046c99125bc88fc9f4cb28.
```
eclipse versioin:  
```
Eclipse IDE for C/C++ Developers

Version: Mars.1 Release (4.5.1)
Build id: 20150924-1200
```

**Comment by paulvi** [comment]
About "MD5 hash is not as expected"


Have you tried other install options?

**Comment by yananzhi** [comment]
@paulvi I have try install GFM in eclipse marketplace, It has the same error info.

**Comment by paulvi** [comment]
waiting author @satyagraha

**Comment by paulvi** [comment]
http://www.nodeclipse.org/updates also has (not latest copy)

**Comment by satyagraha** [comment]
Just installed on Eclipse Mars 4.5.0 64-bit Windows from link in original post without any problem.

**Comment by satyagraha** [comment]
Here are the checksums for that delivery, which show that your error is unexpected:
```
D:\development\eclipse\gfm_viewer\update-site\target>d:\software\fciv\fciv.exe -md5 -add site -r
//
// File Checksum Integrity Verifier version 2.05.
//
Start Time: 01/20/2016 at 08h15'45''

767973dab64b0348eadd63ae78621ad3 site\artifacts.jar
5e765a08502d75dde99af5ff884e8c61 site\content.jar
4c8906fef6edd5fd05df0f020730c865 site\features\code.satyagraha.gfm.viewer.feature_1.9.3.jar
dcdc7953e7e1135179d49b296d038774 site\plugins\code.satyagraha.gfm.viewer.plugin_1.9.3.jar
6e6fcfac21fc9ec089068b55495e513c site\site.xml

End Time..: 01/20/2016 at 08h15'45''


        Processed 3 directories
        Processed 5 files
```
You can download these files directly from http://dl.bintray.com/satyagraha/generic/1.9.3/ and create a local update site in that format. I have just downloaded the plugin jar from there and it's good. The utility I used was https://support.microsoft.com/en-us/kb/841290 .

I suspect you had a broken internet connection during the download, or you have a virus checker enabled which is reporting a false positive match on the jar in question.
