### ISSUE TITLE
Installation not possible (requires bintray login)

### ISSUE THREAD

**Issue by tonit** [satyagraha/gfm_viewer#84]
When using the marketplace client (Eclipse Neon M6):

> error occurred while collecting items to be installed
session context was:(profile=SDKProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at: http://dl.bintray.com/satyagraha/generic/2.0.1/features/code.satyagraha.gfm.viewer.feature_2.0.1.jar. Login canceled by user.
Unable to read repository at: http://dl.bintray.com/satyagraha/generic/2.0.1/plugins/code.satyagraha.gfm.viewer.plugin_2.0.1.jar. Login canceled by user.`

Same with installation via tycho.

**Comment by paulvi** [comment]
Code shows that there was release 18 hours ago.

@satyagraha

**Comment by satyagraha** [comment]
OK, my fault, I forgot to formally publish the uploaded files, now they should be available.
