### ISSUE TITLE
Invocation methods?

### ISSUE THREAD

**Issue by sinforosoft** [satyagraha/gfm_viewer#86]
Hi!

Is it possible to invoke gfm_viewer directly from java? Or even better, from maven? I am trying to use eclipse for markdown editing and maven for site generation. I know maven now supports markdown, but differences with gfm are quite remarkable, so i get ugly results with maven default site plugin. A common generation engine is what I need for uniform results ...

**Comment by satyagraha** [comment]
See https://stackoverflow.com/questions/7694887/is-there-a-command-line-utility-for-rendering-github-flavored-markdown for some ideas.
